spring:
  application:
    name: spring-modulith-demo
  docker:
    compose:
      lifecycle-management: start_only
  sql:
    init:
      mode: always
  modulith:
    events:
      republish-outstanding-events-on-restart: true
      jdbc:
        schema-initialization:
          enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5432/mydatabase
    username: myuser
    password: secret
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    bootstrap-servers: localhost:9092
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/realms/master
          jwk-set-uri: http://localhost:8180/realms/master/protocol/openid-connect/certs

weather:
  api:
    key: demo  # Replace with your actual OpenWeatherMap API key
    base-url: https://api.openweathermap.org/data/2.5
management:
  endpoints:
    web:
      exposure:
        include: modulith, health, info, prometheus

springdoc:
  swagger-ui:
    path: "/apidoc"
    groups-order: desc
logging:
  level:
    org.springframework.jdbc.datasource.init: DEBUG
    org.springframework.boot.sql.init: DEBUG

